# PICloud Group 2 Deployment Phase

# Database Pod

apiVersion: v1
kind: Pod
metadata:
  name: pod-pidev-database
  labels:
    app: label-pod-pidev-database
spec:
  containers:
  - name: pidev-database
    image: mysql:latest
    env:
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "true"

    ports:
    - containerPort: 3306
      name: cport-3306    
  restartPolicy: Always
  
---

# Database Service ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: service-pidev-database-clusterip
  labels:
    app: label-service-pidev-database-clusterip
spec:
  selector:
    app: label-pod-pidev-database
  ports:
  - port: 3306
    name: port-3306
    targetPort: 3306

---

# Backend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-backend
  labels:
    app: label-deployment-pidev-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-deployment-pidev-backend
  template:
    metadata:
      labels:
        app: label-deployment-pidev-backend
    spec:
      containers:
      - name: pidev-backend
        image: mariembenjaballah/carrerboostbackenddee:latest
        ports:
        - containerPort: 9000
          name: cport-9000
        - containerPort: 587
          name: cport-587
  restartPolicy: Always
---

# Backend Service NodePort

apiVersion: v1
kind: Service
metadata:
  name: service-pidev-backend-nodeport
  labels:
    app: label-service-pidev-backend-nodeport
spec:
  selector:
    app: label-deployment-pidev-backend
  ports:
  - port: 9000
    name: port-9000
    targetPort: 9000
    nodePort: 30001
  - port: 587  
    name: port-587
    targetPort: 587
    nodePort: 30003
  type: NodePort
  
---

# Frontend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidev-frontend
  labels:
    app: label-deployment-pidev-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-deployment-pidev-frontend
  template:
    metadata:
      labels:
        app: label-deployment-pidev-frontend
    spec:
      containers:
      - name: pidev-frontend
        image: mariembenjaballah/carrerboostfrontt:latest
        ports:
        - containerPort: 80
          name: cport-80
  restartPolicy: Always
    
---

# Frontend Service NodePort

apiVersion: v1
kind: Service
metadata:
  name: service-pidev-frontend-nodeport
  labels:
    app: label-service-pidev-frontend-nodeport
spec:
  selector:
    app: label-deployment-pidev-frontend
  ports:
  - port: 80 
    name: port-80
    targetPort: 80
    nodePort: 30002
  type: NodePort
  
---